### ISSUE TITLE
[General Question] Does this CLI understand updates from other writers?

### ISSUE THREAD

**Issue by flyingImer** [InfuseAI/ArtiV#11]
Let’s say a S3 prefix is being used by multiple services. I want to update certain object content locally and write it back to the same S3 object key IFF no other service touch that one before my work. Would it possible with this CLI?

Like for my own work, I interact with that S3 prefix with this CLI, will I be able to easily pull and tell objects added/updated/deleted by others? 

Curious how does the versioning work in such case?

**Comment by popcornylu** [comment]
Yes, sure. The collaboration is fundamental requirement for a version control system. Just like git, there would be multiple users push commits to repository. 

In ArtiV, you can use
1. `art log` to see the commit logs
2. use `art pull` to pull the latest version to local. 
3. If both local and remote have changes, we can use `art pull --sync` or `art pull --merge` or default `art pull` to merge remote data to local
4. You can use `art pull --dry-run` or `art push --dry-run` to see the different between local and remote in two direction.

About the underlying design, you can check the document here
https://github.com/InfuseAI/artiv#how-it-works
Actually, the file structure is similar as `.git`. Welcome to ask more questions about any implementation detail.

**Comment by flyingImer** [comment]
Thanks for the clarification! it is still unclear to me if the `.git` is maintained locally (my temporary storage, like on my laptop) or remotely (e.g., S3, the destination storage of choice)?

**Comment by popcornylu** [comment]
The `.git` like files are stored at the remote, but there are metadata cache locally.

The repository stucture
```
<artifact repository root>
├── commits
│   └── <commits>
├── objects
│   ├── 03
│   │   └── cfd743661f07975fa2f1220c5194cbaff48451
│   ├── 23
│   │   └── 715d393e1b723b249642a586597426885f64d1
│   ├── 2b
│   │   └── 77b0d6a5f3bd047fb2c6e44bbb22822f773f94
│   ├── 32
│   │   └── e2eb1b2f4b757fcc3e112d57ca702c65dad526
│   ├── 6d
│   │   └── 7cb1f44cb598a0db93f912791a1c20e3bd7c6b
│   ├── 84
│   │   └── 44869206da2a25b8ee79a8959ed4b34144f2a8
│   ├── ac
│   │   └── 9bcb803e59cd45610d87f2b683319420e7f76b
│   └── d7
│       └── 153b344c84ae187e2a894688310f1956dc45b7
└── refs
    ├── latest
    └── tags
        ├── v1.0.0    
        └── v1.0.1
```

local structure
```
.
├── .DS_Store
├── .art
│   ├── commits
│   │   └── <commits>
│   ├── config
│   └── refs
│       ├── tags
│       │   └── <tags>
│       └── latest
└── <your workspace files>
```

Comparing to git, 

**Git**: git remote repo is like a bare repo. The local git repo contains workspace + repo (which contains the whole files and metadata)
**ArtiV**: arti repo at the remote is like a bare repo of git. The local is only the workspace  (and some metadata cache).

So the nature of git local repo which save all files of all version makes git not suitable for large files.
